{
  logStore.afterPropertiesSet();
  Throwable ex=new RuntimeException("test exception");
  ex.fillInStackTrace();
  logStore.debug(repoUrl,"debug message 1");
  logStore.error(repoUrl,"error message 1",ex);
  logStore.info(repoUrl,"info message 1");
  logStore.debug(repoUrl,"debug message 2");
  logStore.error(repoUrl,"error message 2",ex);
  logStore.info(repoUrl,"info message 2");
  assertEquals(6,logStore.getLogEntries(0,10,INFO,DEBUG,ERROR).size());
  assertEquals(4,logStore.getLogEntries(0,10,INFO,DEBUG).size());
  assertEquals(4,logStore.getLogEntries(0,10,INFO,ERROR).size());
  assertEquals(4,logStore.getLogEntries(0,10,DEBUG,ERROR).size());
  assertEquals(2,logStore.getLogEntries(0,10,INFO).size());
  assertEquals(2,logStore.getLogEntries(0,10,ERROR).size());
  assertEquals(2,logStore.getLogEntries(0,10,DEBUG).size());
}
